// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -destination=mock/transaction.go -source transaction.go
//

// Package mock_transaction is a generated GoMock package.
package mock_transaction

import (
	context "context"
	reflect "reflect"

	transaction "github.com/vedga/lib-go-transaction"
	data "github.com/vedga/lib-go-transaction/data"
	gomock "go.uber.org/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// AddRollbackTask mocks base method.
func (m *MockTransaction) AddRollbackTask(kind string, setup ...data.Setup) error {
	m.ctrl.T.Helper()
	varargs := []any{kind}
	for _, a := range setup {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddRollbackTask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRollbackTask indicates an expected call of AddRollbackTask.
func (mr *MockTransactionMockRecorder) AddRollbackTask(kind any, setup ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{kind}, setup...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRollbackTask", reflect.TypeOf((*MockTransaction)(nil).AddRollbackTask), varargs...)
}

// AddTask mocks base method.
func (m *MockTransaction) AddTask(kind string, setup ...data.Setup) error {
	m.ctrl.T.Helper()
	varargs := []any{kind}
	for _, a := range setup {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddTask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTask indicates an expected call of AddTask.
func (mr *MockTransactionMockRecorder) AddTask(kind any, setup ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{kind}, setup...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockTransaction)(nil).AddTask), varargs...)
}

// Attempt mocks base method.
func (m *MockTransaction) Attempt() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attempt")
	ret0, _ := ret[0].(uint)
	return ret0
}

// Attempt indicates an expected call of Attempt.
func (mr *MockTransactionMockRecorder) Attempt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attempt", reflect.TypeOf((*MockTransaction)(nil).Attempt))
}

// ClearData mocks base method.
func (m *MockTransaction) ClearData() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearData")
}

// ClearData indicates an expected call of ClearData.
func (mr *MockTransactionMockRecorder) ClearData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearData", reflect.TypeOf((*MockTransaction)(nil).ClearData))
}

// DataCount mocks base method.
func (m *MockTransaction) DataCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// DataCount indicates an expected call of DataCount.
func (mr *MockTransactionMockRecorder) DataCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataCount", reflect.TypeOf((*MockTransaction)(nil).DataCount))
}

// Encode mocks base method.
func (m *MockTransaction) Encode() (data.Bytes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode")
	ret0, _ := ret[0].(data.Bytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockTransactionMockRecorder) Encode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockTransaction)(nil).Encode))
}

// ID mocks base method.
func (m *MockTransaction) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockTransactionMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockTransaction)(nil).ID))
}

// MarkRollback mocks base method.
func (m *MockTransaction) MarkRollback(cause string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRollback", cause)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRollback indicates an expected call of MarkRollback.
func (mr *MockTransactionMockRecorder) MarkRollback(cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRollback", reflect.TypeOf((*MockTransaction)(nil).MarkRollback), cause)
}

// NewTask mocks base method.
func (m *MockTransaction) NewTask(kind string, setup ...data.Setup) (transaction.Task, error) {
	m.ctrl.T.Helper()
	varargs := []any{kind}
	for _, a := range setup {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewTask", varargs...)
	ret0, _ := ret[0].(transaction.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewTask indicates an expected call of NewTask.
func (mr *MockTransactionMockRecorder) NewTask(kind any, setup ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{kind}, setup...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTask", reflect.TypeOf((*MockTransaction)(nil).NewTask), varargs...)
}

// PopData mocks base method.
func (m *MockTransaction) PopData() (data.Bytes, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopData")
	ret0, _ := ret[0].(data.Bytes)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// PopData indicates an expected call of PopData.
func (mr *MockTransactionMockRecorder) PopData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopData", reflect.TypeOf((*MockTransaction)(nil).PopData))
}

// PushData mocks base method.
func (m *MockTransaction) PushData(items ...data.Bytes) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range items {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PushData", varargs...)
}

// PushData indicates an expected call of PushData.
func (mr *MockTransactionMockRecorder) PushData(items ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushData", reflect.TypeOf((*MockTransaction)(nil).PushData), items...)
}

// QueueEncodedTask mocks base method.
func (m *MockTransaction) QueueEncodedTask(encodedTask data.Bytes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueEncodedTask", encodedTask)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueEncodedTask indicates an expected call of QueueEncodedTask.
func (mr *MockTransactionMockRecorder) QueueEncodedTask(encodedTask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueEncodedTask", reflect.TypeOf((*MockTransaction)(nil).QueueEncodedTask), encodedTask)
}

// QueueRollbackTask mocks base method.
func (m *MockTransaction) QueueRollbackTask(kind string, task transaction.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueRollbackTask", kind, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueRollbackTask indicates an expected call of QueueRollbackTask.
func (mr *MockTransactionMockRecorder) QueueRollbackTask(kind, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueRollbackTask", reflect.TypeOf((*MockTransaction)(nil).QueueRollbackTask), kind, task)
}

// QueueTask mocks base method.
func (m *MockTransaction) QueueTask(kind string, task transaction.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueTask", kind, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueTask indicates an expected call of QueueTask.
func (mr *MockTransactionMockRecorder) QueueTask(kind, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueTask", reflect.TypeOf((*MockTransaction)(nil).QueueTask), kind, task)
}

// Rollback mocks base method.
func (m *MockTransaction) Rollback() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTransactionMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTransaction)(nil).Rollback))
}

// Run mocks base method.
func (m *MockTransaction) Run(ctx context.Context, kind string, tx transaction.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, kind, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTransactionMockRecorder) Run(ctx, kind, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTransaction)(nil).Run), ctx, kind, tx)
}
