// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -destination=mock/transaction.go -source transaction.go
//

// Package mock_transaction is a generated GoMock package.
package mock_transaction

import (
	context "context"
	reflect "reflect"

	transaction "github.com/vedga/lib-go-transaction"
	data "github.com/vedga/lib-go-transaction/data"
	gomock "go.uber.org/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// AddRollbackTask mocks base method.
func (m *MockTransaction) AddRollbackTask(kind string, setup ...data.Setup) error {
	m.ctrl.T.Helper()
	varargs := []any{kind}
	for _, a := range setup {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddRollbackTask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRollbackTask indicates an expected call of AddRollbackTask.
func (mr *MockTransactionMockRecorder) AddRollbackTask(kind any, setup ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{kind}, setup...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRollbackTask", reflect.TypeOf((*MockTransaction)(nil).AddRollbackTask), varargs...)
}

// AddTask mocks base method.
func (m *MockTransaction) AddTask(kind string, setup ...data.Setup) error {
	m.ctrl.T.Helper()
	varargs := []any{kind}
	for _, a := range setup {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddTask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTask indicates an expected call of AddTask.
func (mr *MockTransactionMockRecorder) AddTask(kind any, setup ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{kind}, setup...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockTransaction)(nil).AddTask), varargs...)
}

// Encode mocks base method.
func (m *MockTransaction) Encode() (data.Bytes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode")
	ret0, _ := ret[0].(data.Bytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockTransactionMockRecorder) Encode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockTransaction)(nil).Encode))
}

// NewTask mocks base method.
func (m *MockTransaction) NewTask(kind string, setup ...data.Setup) (transaction.Task, error) {
	m.ctrl.T.Helper()
	varargs := []any{kind}
	for _, a := range setup {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewTask", varargs...)
	ret0, _ := ret[0].(transaction.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewTask indicates an expected call of NewTask.
func (mr *MockTransactionMockRecorder) NewTask(kind any, setup ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{kind}, setup...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTask", reflect.TypeOf((*MockTransaction)(nil).NewTask), varargs...)
}

// NextAttempt mocks base method.
func (m *MockTransaction) NextAttempt(maxRetries uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextAttempt", maxRetries)
	ret0, _ := ret[0].(error)
	return ret0
}

// NextAttempt indicates an expected call of NextAttempt.
func (mr *MockTransactionMockRecorder) NextAttempt(maxRetries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextAttempt", reflect.TypeOf((*MockTransaction)(nil).NextAttempt), maxRetries)
}

// QueueRollbackTask mocks base method.
func (m *MockTransaction) QueueRollbackTask(kind string, task transaction.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueRollbackTask", kind, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueRollbackTask indicates an expected call of QueueRollbackTask.
func (mr *MockTransactionMockRecorder) QueueRollbackTask(kind, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueRollbackTask", reflect.TypeOf((*MockTransaction)(nil).QueueRollbackTask), kind, task)
}

// QueueTask mocks base method.
func (m *MockTransaction) QueueTask(kind string, task transaction.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueTask", kind, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueTask indicates an expected call of QueueTask.
func (mr *MockTransactionMockRecorder) QueueTask(kind, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueTask", reflect.TypeOf((*MockTransaction)(nil).QueueTask), kind, task)
}

// Run mocks base method.
func (m *MockTransaction) Run(ctx context.Context, tx transaction.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTransactionMockRecorder) Run(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTransaction)(nil).Run), ctx, tx)
}

// SetRollback mocks base method.
func (m *MockTransaction) SetRollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRollback indicates an expected call of SetRollback.
func (mr *MockTransactionMockRecorder) SetRollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRollback", reflect.TypeOf((*MockTransaction)(nil).SetRollback))
}
